### ISSUE TITLE
Create recipients throws exception on 201

### ISSUE THREAD

**Issue by RBoelter** [rapidmail/rapidmail-apiv3-client-php#6]
Hi,
I try to create user via $response = $service->create(/* PAYLOAD */, /* OPTIONAL MODIFIER */);
The user is created and the response is 201, but it seems that an exception is thrown on 201.

```
try {
  $recipientsService = $this->newsletterClient->recipients();
  $response = $recipientsService->create($payload, $modifier);
 } catch (ApiClientException $e) {
  $this->logger->error($e->getMessage());
}
```

`Jul  6 15:24:44 |ERROR| APP    API error 201 when requesting https://apiv3.emailsys.net/v1/recipients?send_activationmail=no&track_stats=yes. Detail: {"id":"10198387","recipientlist_id":"1744", ... }}}`

Best,
Ronny

**Comment by eth8505** [comment]
@RBoelter I believe this was also reported to rapidmail support last week and we haven't been able to reproduce it yet.
Can you provide more information on your system like operating system, PHP version and dependency versions either via ```composer show``` or by providing us with your composer.lock ?

**Comment by RBoelter** [comment]
@eth8505 Sure,
OS: Windows 10
PHP Version: 
```
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans
```

composer show:
```
doctrine/annotations                 1.10.3  Docblock Annotations Parser
doctrine/cache                       1.10.1  PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.5   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      2.13.3  PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces, proxies, event system and much more.
doctrine/dbal                        2.10.2  Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             2.1.0   Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  2.1.2   Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.0   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   1.4.3   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.3.1   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  2.2.1   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to use and a powerful tool.
doctrine/orm                         v2.7.3  Object-Relational-Mapper for PHP
doctrine/persistence                 1.3.7   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                  1.2.1   The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional functionality on top of the reflection functionality that comes with PHP. It allows you to get the reflection information about classes, methods...
doctrine/sql-formatter               1.1.0   a PHP SQL highlighting library
egulias/email-validator              2.1.17  A library for validating emails against several RFCs
firebase/php-jwt                     v4.0.0  A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
guzzlehttp/guzzle                    6.5.4   Guzzle is a PHP HTTP client library
guzzlehttp/promises                  v1.3.1  Guzzle promises library
guzzlehttp/psr7                      1.6.1   PSR-7 message implementation that also provides common utility methods
knpuniversity/oauth2-client-bundle   v2.1.0  Integration with league/oauth2-client to provide services
laminas/laminas-code                 3.4.1   Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.2.1   Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.0.4   Alias legacy ZF class names to Laminas Project equivalents.
league/oauth2-client                 2.2.1   OAuth 2.0 Client Library
monolog/monolog                      2.1.0   Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser                     v4.5.0  A PHP parser written in PHP
ocramius/package-versions            1.8.0   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager               2.8.0   A library providing utilities to generate, instantiate and generally operate with Object Proxies
phpdocumentor/reflection-common      2.1.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.1.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          1.1.0   A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                            1.0.1   Common interface for caching libraries
psr/container                        1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0   Standard interfaces for event handling.
psr/http-message                     1.0.1   Common interface for HTTP messages
psr/link                             1.0.0   Common interfaces for HTTP links
psr/log                              1.1.3   Common interface for logging libraries
ralouphie/getallheaders              3.0.3   A polyfill for getallheaders.
rapidmail/rapidmail-apiv3-client-php 1.0.1   rapidmail API v3 client
sensio/framework-extra-bundle        v5.5.6  This bundle provides a way to configure your controllers with annotations
stevenmaguire/oauth2-keycloak        2.1.0   Keycloak OAuth 2.0 Client Provider for The PHP League OAuth2-Client
symfony/asset                        v5.1.2  Symfony Asset Component
symfony/browser-kit                  v5.1.2  Symfony BrowserKit Component
symfony/cache                        v5.1.2  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.1.2  Generic abstractions related to caching
symfony/config                       v5.1.2  Symfony Config Component
symfony/console                      v5.1.2  Symfony Console Component
symfony/css-selector                 v5.1.2  Symfony CssSelector Component
symfony/debug-bundle                 v5.1.2  Symfony DebugBundle
symfony/debug-pack                   v1.0.8  A debug pack for Symfony projects
symfony/dependency-injection         v5.1.2  Symfony DependencyInjection Component
symfony/deprecation-contracts        v2.1.2  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.1.2  Symfony Doctrine Bridge
symfony/dom-crawler                  v5.1.2  Symfony DomCrawler Component
symfony/dotenv                       v5.1.2  Registers environment variables from a .env file
symfony/error-handler                v5.1.2  Symfony ErrorHandler Component
symfony/event-dispatcher             v5.1.2  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.1.2  Generic abstractions related to dispatching event
symfony/expression-language          v5.1.2  Symfony ExpressionLanguage Component
symfony/filesystem                   v5.1.2  Symfony Filesystem Component
symfony/finder                       v5.1.2  Symfony Finder Component
symfony/flex                         v1.8.4  Composer plugin for Symfony
symfony/form                         v5.1.2  Symfony Form Component
symfony/framework-bundle             v5.1.2  Symfony FrameworkBundle
symfony/http-client                  v5.1.2  Symfony HttpClient component
symfony/http-client-contracts        v2.1.2  Generic abstractions related to HTTP clients
symfony/http-foundation              v5.1.2  Symfony HttpFoundation Component
symfony/http-kernel                  v5.1.2  Symfony HttpKernel Component
symfony/inflector                    v5.1.2  Symfony Inflector Component
symfony/intl                         v5.1.2  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                       v5.1.2  Symfony Mailer Component
symfony/maker-bundle                 v1.19.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                         v5.1.2  A library to manipulate MIME messages
symfony/monolog-bridge               v5.1.2  Symfony Monolog Bridge
symfony/monolog-bundle               v3.5.0  Symfony MonologBundle
symfony/notifier                     v5.1.2  A library to notify messages
symfony/options-resolver             v5.1.2  Symfony OptionsResolver Component
symfony/orm-pack                     v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge               v5.1.2  Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme       v1.17.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.17.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.17.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.17.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.17.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.17.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.17.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                      v5.1.2  Symfony Process Component
symfony/profiler-pack                v1.0.4  A pack for the Symfony web profiler
symfony/property-access              v5.1.2  Symfony PropertyAccess Component
symfony/property-info                v5.1.2  Symfony Property Info Component
symfony/routing                      v5.1.2  Symfony Routing Component
symfony/security-bundle              v5.1.2  Symfony SecurityBundle
symfony/security-core                v5.1.2  Symfony Security Component - Core Library
symfony/security-csrf                v5.1.2  Symfony Security Component - CSRF Library
symfony/security-guard               v5.1.2  Symfony Security Component - Guard
symfony/security-http                v5.1.2  Symfony Security Component - HTTP Integration
symfony/serializer                   v5.1.2  Symfony Serializer Component
symfony/serializer-pack              v1.0.3  A pack for the Symfony serializer
symfony/service-contracts            v2.1.2  Generic abstractions related to writing services
symfony/stopwatch                    v5.1.2  Symfony Stopwatch Component
symfony/string                       v5.1.2  Symfony String component
symfony/test-pack                    v1.0.6  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                  v5.1.2  Symfony Translation Component
symfony/translation-contracts        v2.1.2  Generic abstractions related to translation
symfony/twig-bridge                  v5.1.2  Symfony Twig Bridge
symfony/twig-bundle                  v5.1.2  Symfony TwigBundle
symfony/twig-pack                    v1.0.0  A Twig pack for Symfony projects
symfony/validator                    v5.1.2  Symfony Validator Component
symfony/var-dumper                   v5.1.2  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v5.1.2  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                     v5.1.2  Symfony WebLink Component
symfony/web-profiler-bundle          v5.1.2  Symfony WebProfilerBundle
symfony/webpack-encore-bundle        v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                         v5.1.2  Symfony Yaml Component
twig/extra-bundle                    v3.0.3  A Symfony bundle for extra Twig extensions
twig/twig                            v3.0.3  Twig, the flexible, fast, and secure template language for PHP
webimpress/safe-writer               2.0.1   Tool to write files safely, to avoid race conditions
webmozart/assert                     1.8.0   Assertions to validate method input/output with nice error messages.

```

**Comment by eth8505** [comment]
@RBoelter looks OK to me. I just tried reproducing the problem on
Ubuntu Linux with
* PHP 7.1.33
* PHP 7.3.19
* PHP 7.4.7
Windows 10 (1909)
* PHP 7.4.8

Created a recipient just fine with all of the above. Any chance you could Get me the getTraceAsString() output of the original guzzle exception passed into ApiException::fromGuzzleException() ? 

Slightly OT: We should really be providing the original guzzle exception as $previous parameter in the API exception, will put that on the list for the next release.

**Comment by RBoelter** [comment]
@eth8505 Here is the trace:

```
[Application    ] Jul  8 08:29:19 |ERROR| APP    #0 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-apiv3-client-php\src\Http\HttpClientFacade.php(36): Rapidmail\ApiClient\Exception\ApiException::fromGuzzleException(Object(GuzzleHttp\Exception\RequestException)) #1 D:\Arbeitsordner\P
hpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-apiv3-client-php\src\Service\V1\Api\Recipients\Recipient\RecipientService.php(240): Rapidmail\ApiClient\Http\HttpClientFacade->request('POST', 'recipients', Array) #2 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-apiv3-clien
t-php\src\Service\V1\Api\Recipients\Recipient\RecipientService.php(137): Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\RecipientService->upsert('POST', 'recipients', Object(Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\Parameter\RecipientCreateParam), Object(Rapidmail\ApiClient\Service\V1\Ap
i\Recipients\Recipient\Parameter\RecipientCreateQueryParam)) #3 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\src\Service\RapidMailService.php(137): Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\RecipientService->create(Array, Array) #4 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\src\Controlle
r\ClientController.php(163): App\Service\RapidMailService->saveClient(Object(App\Entity\Client), '1744') #5 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel\HttpKernel.php(157): App\Controller\ClientController->executeNewsletter(Object(Symfony\Component\HttpFoundation\Request)) #6 D:\
Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel\HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel\Kernel.php(196): Symfony\Component\H
ttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\public\index.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 {main}

```

**Comment by RBoelter** [comment]
@eth8505 I get the same error with update() (exception thrown on 200).
```
[Application    ] Jul  8 09:10:36 |ERROR| APP    API error 200 when requesting https://apiv3.emailsys.net/v1/recipients/10198387. Detail: {"id":"10198387"...}
```

```
[Application    ] Jul  8 09:12:29 |ERROR| APP    #0 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-apiv3-client-php\src\Http\HttpClientFacade.php(36): Rapidmail\ApiClient\Exception\ApiException::fromGuzzleException(Object(GuzzleHttp\Exception\RequestException)) #1 D:\Arbeitsordner\P
hpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-apiv3-client-php\src\Service\V1\Api\Recipients\Recipient\RecipientService.php(240): Rapidmail\ApiClient\Http\HttpClientFacade->request('PATCH', 'recipients/1019...', Array) #2 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\rapidmail\rapidmail-ap
iv3-client-php\src\Service\V1\Api\Recipients\Recipient\RecipientService.php(155): Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\RecipientService->upsert('PATCH', 'recipients/1019...', Object(Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\Parameter\RecipientCreateParam), Object(Rapidmail\ApiCl
ient\Service\V1\Api\Recipients\Recipient\Parameter\RecipientCreateQueryParam)) #3 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\src\Service\RapidMailService.php(164): Rapidmail\ApiClient\Service\V1\Api\Recipients\Recipient\RecipientService->update('10198387', Array) #4 D:\Arbeitsordner\PhpstormProjects\zpid-
dashboard\src\Controller\ClientController.php(166): App\Service\RapidMailService->updateClient(Object(App\Entity\Client), '10198387', '1744') #5 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel\HttpKernel.php(157): App\Controller\ClientController->executeNewsletter(Object(Symfony\Comp
onent\HttpFoundation\Request)) #6 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel\HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\vendor\symfony\http-kernel
\Kernel.php(196): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 D:\Arbeitsordner\PhpstormProjects\zpid-dashboard\public\index.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #9 {main}

```


The delete function works fine.
Another error I get is when I put the 'recipientlist_id' in the data array when using update. 
Then this happens:
```
[Application    ] Jul  8 08:56:02 |ERROR| APP    API error 400 when requesting https://apiv3.emailsys.net/v1/recipients/10198387. Detail: {"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Bad Request","status":400,"detail":"Unrecognized field \"recipientlist_id\""}
```
According to the documentation (https://developer.rapidmail.wiki/documentation.html?urls.primaryName=Recipients#/Recipients/patch_recipients__recipient_id_) the use of the ` recipientlist_id' seems to be ok.
I don't know if the use of this ID is important when updating, because I have no clue if the user data is stored globally or if it is individual entries for each list, like different mail address for each list or so.

**Comment by RBoelter** [comment]
@eth8505 It seems to work with PHP 7.4.8, that's weird.

**Comment by eth8505** [comment]
@RBoelter i just played around with PHP builds for win10, I can reproduce the bug with PHP 7.4.5, but not with any newer version. Since I don't have 7.4.5 available for linux, I can't test it on linux. I recommend upgrading your PHP on windows, as it seems to work with 7.4.6 and higher.  
I will discuss with the team if we can explicitly drop support for PHP 7.4.5 just to be sure.

**Comment by RBoelter** [comment]
@eth8505 Yes, I have already updated to 7.4.8. I will deploy this to my Unix server later, but I think it will work. Thanks for your help ;-)
